registrants:
  - name: "VANGUARD HORIZON FUNDS"
    cik: "0000932471"
    series_ids: ["S000002594"]
    class_ids: []
  - name: "VANGUARD CHESTER FUNDS"
    cik: "0000752177"
    series_ids: ["S000002568"]
    class_ids: []  
  - name: "FIDELITY CONTRAFUND"
    cik: "0000024238"
    series_ids: ["S000006037"]
    class_ids: []
  - name: "HARBOR FUNDS"
    cik: "0000793769"
    series_ids: ["S000000681"]
    class_ids: []